name = "gramfel"
main = "src/index.ts"
compatibility_date = "2023-05-11"

[triggers]
crons = [
    "0 17 * * *",
    "30 12 * * *",
    "30 13 * * *",
    "30 1 * * *",
]

[observability]
enabled = true
