name = "gramfel"
main = "src/index.ts"
compatibility_date = "2023-05-11"

[triggers]
crons = [
    "0 17 * * *",
    "30 1 * * *",
    "30 2 * * *",
    "0 14 * * 2",
]

[observability]
enabled = true
